Traceback (most recent call last):
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tavenard_r/py38_data/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import HTML
from celluloid import Camera

f = np.zeros((12, ))
f[:4] = -1.
f[4:8] = 1.
f[8:] = -1.

length = 60

fig = plt.figure()
camera = Camera(fig)

for pos in range(5, 35):
    x = np.zeros((100, ))
    x[pos:pos+length] = np.sin(np.linspace(0, 2 * np.pi, num=length))

    act = np.correlate(x, f, mode='same')

    plt.subplot(2, 1, 1)
    plt.plot(x, 'b-')
    plt.title("Input time series")
    fig2 = plt.subplot(2, 1, 2)
    plt.plot(act, 'r-')
    plt.title("Activation map")

    axes2 = fig.add_axes([0.3, 0.5, 0.3, 0.3]) # renvoie un objet Axes
    axes2.plot(f, 'k-')
    axes2.title("Filter")

    plt.tight_layout()
    camera.snap()

anim = camera.animate()
plt.close()

HTML(anim.to_jshtml())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-b603024e65c9>[0m in [0;36m<module>[0;34m[0m
[1;32m     27[0m     [0maxes2[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0madd_axes[0m[0;34m([0m[0;34m[[0m[0;36m0.3[0m[0;34m,[0m [0;36m0.5[0m[0;34m,[0m [0;36m0.3[0m[0;34m,[0m [0;36m0.3[0m[0;34m][0m[0;34m)[0m [0;31m# renvoie un objet Axes[0m[0;34m[0m[0;34m[0m[0m
[1;32m     28[0m     [0maxes2[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mf[0m[0;34m,[0m [0;34m'k-'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 29[0;31m     [0maxes2[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m"Filter"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     30[0m [0;34m[0m[0m
[1;32m     31[0m     [0mplt[0m[0;34m.[0m[0mtight_layout[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'Text' object is not callable
TypeError: 'Text' object is not callable

